### ISSUE TITLE
currency concurrent initialization

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dgg/nmoneys#30]
```
When trying to make a NMoneys.Currency.Get(<<currencyIso>>) of an uninitialised 
currency from multiple concurrent System.Threading.Tasks.Task you will get:

System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NMoneys.Support.ThreadSafeCache`2.Add(TKey key, TValue value)
   at NMoneys.Currency.Get(CurrencyIsoCode isoCode)

You have in the attach the unit test to reproduce this.

I may suggest to use ConcurrentDictionary<TKey, TValue> to keep the initialized 
currencies.

Thank you for your useful library!

Regards,
Cosmin


```

Original issue reported on code.google.com by `cosmin.n...@gmail.com` on 23 Feb 2015 at 9:27

Attachments:
* [NMoneysCurrencyInitializationTests.cs](https://storage.googleapis.com/google-code-attachments/nmoneys/issue-30/comment-0/NMoneysCurrencyInitializationTests.cs)

**Comment by dgg** [comment]
Releasing 4.0 today
